[package]
name = "libblkid-rs"
version = "0.1.0"
authors = ["John Baublitz <jbaublitz@redhat.com>"]
edition = "2018"
description = "High level bindings for libblkid"
license = "MPL-2.0"
documentation = "https://docs.rs/libblkid-rs"
homepage = "https://stratis-storage.github.io"
repository = "https://github.com/stratis-storage/libblkid-rs"
exclude = [".github/*", ".gitignore"]

[dependencies.libblkid-rs-sys]
version = "0.1.0"
path = "./libblkid-rs-sys"

[dependencies]
either = "1.5.0"
libc = "0.2.65"
uuid = "0.8.0"

[features]
default = []
deprecated = []
