---
name: libblkid CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks:
    strategy:
      matrix:
        include:
          # MANDATORY CHECKS USING CURRENT DEVELOPMENT COMPILER
          - components: rustfmt
            toolchain: 1.52.1
            task: fmt-travis
          - components: clippy
            toolchain: 1.52.1
            task: clippy
          # MANDATORY TESTING USING LOWEST SUPPORTED COMPILER
          - components: cargo
            toolchain: 1.49.0
            task: test
          # MANDATORY TESTING ON STABLE
          - components: cargo
            toolchain: stable
            task: build
          - components: cargo
            toolchain: stable
            task: test
          - components: cargo
            toolchain: stable
            task: docs-travis
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: ${{ matrix.components }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libblkid-dev
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        run: make -f Makefile ${{ matrix.task }}

  # VERIFICATION OF TEST INFRASTRUCTURE
  yamllint:
    env:
      TASK: yamllint
      PYTHON: 3.8.6
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON }}
      - name: Install dependencies
        run: pip3 install yamllint==1.26.0
      - name: Run yamllint
        run: make -f Makefile $TASK
