---
name: libblkid CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
    paths-ignore:
      - "CHANGES.txt"
      - "**/README.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "CHANGES.txt"
      - "**/README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks:
    strategy:
      matrix:
        include:
          # MANDATORY CHECKS USING CURRENT DEVELOPMENT COMPILER
          - components: rustfmt
            toolchain: 1.60.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            task: fmt-ci
          - components: clippy
            toolchain: 1.60.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            task: clippy
          - components: cargo
            toolchain: 1.60.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            task: build
          - components: cargo
            toolchain: 1.60.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            task: test
          - components: cargo
            toolchain: 1.60.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            task: docs-ci
          # MANDATORY TESTING USING LOWEST SUPPORTED COMPILER
          - components: cargo
            toolchain: 1.54.0  # LOWEST SUPPORTED RUST TOOLCHAIN
            task: test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: ${{ matrix.components }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libblkid-dev
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        run: make -f Makefile ${{ matrix.task }}

  checks-with-ci-repo:
    strategy:
      matrix:
        include:
          - task: >
              SET_LOWER_BOUNDS=./set_lower_bounds
              MANIFEST_PATH=../../Cargo.toml
              make -f ../../Makefile verify-dependency-bounds
          - task: >
              SET_LOWER_BOUNDS=./set_lower_bounds
              MANIFEST_PATH=../../libblkid-rs-sys/Cargo.toml
              make -f ../../Makefile verify-dependency-bounds-sys
    runs-on: ubuntu-18.04
    container:
      image: fedora:35  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          clang
          curl
          git
          libblkid-devel
          make
          openssl-devel
          python-requests
          python-semantic_version
      - uses: actions-rs/toolchain@v1
        with:
          components: cargo
          toolchain: 1.60.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
          override: true
      - name: Check out ci repo
        run: git clone https://github.com/stratis-storage/ci.git
      - name: Run ${{ matrix.task }}
        run: ${{ matrix.task }}
        working-directory: ./ci/dependency_management

  # VERIFICATION OF TEST INFRASTRUCTURE
  yamllint:
    runs-on: ubuntu-18.04
    container:
      image: fedora:35  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for Fedora
        run: dnf install -y make yamllint
      - name: Run yamllint
        run: make -f Makefile yamllint
