---
name: libblkid weekly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 20 2 * * 2
  workflow_dispatch:

jobs:
  next-fedora-python-checks:
    strategy:
      matrix:
        include:
          - dependencies: yamllint
            task: yamllint
    runs-on: ubuntu-latest
    container: fedora:39  # NEXT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: >
          dnf install -y
          make
          ${{ matrix.dependencies }}
      - name: make -f Makefile ${{ matrix.task }}
        run: make -f Makefile ${{ matrix.task }}
